### PR TITLE
Converted to Swift 3

### PR DESCRIPTION
**Pull request by vincentneo**
So that it works on Swift 3. (at least it runs)
Haven't got the time to fully test

### CODE REVIEW

**Comment by steve228uk** [comment]
This is great, I'll have a look through and merge soon. Need to tag Swift 2.2 and 2.3 releases first.

**Review by vincentneo — COMMENTED** [review]
Updated the Example project to Swift 3 as well.

**Review by vincentneo — COMMENTED** [review]
Updated the uncommented parts (in example) to Swift 3 as well

**Review by vincentneo — COMMENTED** [review]
Changed SRTabLocation to follow Swift 3 consistency to use lowerCamelCase for properties.

**Pull request closed without merging**
